### ISSUE TITLE
Query objects with relations

### ISSUE THREAD

**Issue by TomClarkson** [heroicpixels/filterable#1]
Do you have any plans to implement an Eloquent way to query multiple parameters on objects with relations. For example /posts?category_id=22&tags=foo,bar,baz&title=foobar+post+title

**Comment by Ben-Speakman** [comment]
The above solutions filters the related objects. But if you want to filter Object on its relations you can use the same idea but instead use `whereHas()`

```php
$objects = Object::with(['categories'])->whereHas('categories', function($q){
	$q->filterColumns(['category' => 'cat_object.cat_id']);
})->filterColumns($columns)->get()->toArray();
```
