### ISSUE TITLE
Extending multiple classes

### ISSUE THREAD

**Issue by keyurshah** [heroicpixels/filterable#7]
Great package! I am likely needing my base Eloquent model to extend Filterable and another class together. What would be a good way of doing that? 

Was thinking I might need to create separate models for those needing Filterable.

Is there anyway that filterable could be used as a trait?

Thanks!

**Comment by heroicpixels** [comment]
You could easily transform it into a trait.  Or make it a standalone class that wraps a DB or Eloquent object.  For an example of the latter see https://gist.github.com/heroicpixels/f70fd94d8d4d5158ba0f.

**Comment by keyurshah** [comment]
thanks, i'll look over that. appreciate the help!
